
// ACTION TYPES

const ACTION_CREATE_PRODUCT = 'ACTION_CREATE_PRODUCT';
const ACTION_GET_PRODUCT = 'ACTION_GET_PRODUCT';
const ACTION_REMOVE_PRODUCT = 'ACTION_REMOVE_PRODUCT';
const ACTION_UPDATE_PRODUCT = 'ACTION_UPDATE_PRODUCT';
const ACTION_GET_MERCHANT = 'ACTION_GET_MERCHANT';
const ACTION_CREATE_MERCHANT = 'ACTION_CREATE_MERCHANT';
const ACTION_CHECKOUT = 'ACTION_CHECKOUT';
const ACTION_DO_CHECKOUT_QTY = 'ACTION_DO_CHECKOUT_QTY';
const ACTION_CREATE_STRIPE_CONNECTED_ACCOUNT = 'ACTION_CREATE_STRIPE_CONNECTED_ACCOUNT';
const ACTION_TESTING = 'ACTION_TESTING';
const ACTION_GET_ORDER_SUMMARY_MERCHANT = 'ACTION_GET_ORDER_SUMMARY_MERCHANT';

const ACTION_ADD_PLAN = 'ACTION_ADD_PLAN';
const ACTION_REMOVE_PLAN = 'ACTION_REMOVE_PLAN';

const METADATA_FIELD_LINK_WEBSITE = 'link_website';
const METADATA_FIELD_LINK_FACEBOOK = 'link_facebook';
const METADATA_FIELD_LINK_TWITTER = 'link_twitter';
const METADATA_FIELD_LINK_INSTAGRAM = 'link_instagram';
const METADATA_FIELD_LINK_LINKEDIN = 'link_linkedin';
const METADATA_FIELD_LINK_YOUTUBE = 'link_youtube';

const METADATA_FIELD_MERCHANT_ID = 'merchant_id';

const METADATA_FIELD_THEME_COLOR = 'theme_color';

const METADATA_FIELD_PRODUCT_STATUS = 'product_status';
const DEFAULT_CURRENCY_CAD = 'cad';
const PRICE_RECURRING = 'recurring';
const PRICE_ONE_TIME = 'one_time';

const STRIPE_ACCOUNT = {
    STRIPE_CUSTOM_ACCOUNT: 'custom',
    STRIPE_EXPRESS_ACCOUNT: 'express',
    STRIPE_STANDARD_ACCOUNT: 'standard',
}

const STRIPE_ACCOUNT_BUSINESS_TYPE = {
    STRIPE_ACCOUNT_BUSINESS_TYPE_INDIVIDUAL: 'individual',
    STRIPE_ACCOUNT_BUSINESS_TYPE_COMPANY: 'company',
    STRIPE_ACCOUNT_BUSINESS_TYPE_NONPROFIT: 'non_profit',
    STRIPE_ACCOUNT_BUSINESS_TYPE_GOVERNMENT: 'government_entity', // US ONLY
}

const STRIPE_CHECKOUT_PAYMENT_MODE = {
    PAYMENT: 'payment',
    SETUP: 'setup',
    SUBSCRIPTION: 'subscription'
}

const STRIPE_CHECKOUT_PAYMENT_TYPE = {
    AUTO: 'auto',
    PAY: 'pay',
    BOOK: 'book',
    DONATE:'donate'
}

const DEFAULT_COUNTRY = 'CA';
const EXTERNAL_BANK_ACCOUNT = 'bank_account';
const PLATFORM_DOMAIN = 'https://hellopayouts.com';

// MONEY MONEY HONEY
const PAYOUTS_COMMISSION_ONE_TIME = 0.029;
const PAYOUTS_COMMISSION_SUBSCRIPTION_PERCENT = 2.9;
const PRICES_RETRIEVAL_LIMIT_STRIPE = 100;
const STRIPE_RETRIEVAL_LIMIT = 100;

module.exports = {
    ACTION_CREATE_PRODUCT,
    ACTION_GET_PRODUCT,
    ACTION_GET_MERCHANT,
    ACTION_CREATE_MERCHANT,
    ACTION_REMOVE_PRODUCT,
    ACTION_UPDATE_PRODUCT,
    ACTION_CHECKOUT,
    ACTION_DO_CHECKOUT_QTY,
    ACTION_CREATE_STRIPE_CONNECTED_ACCOUNT,
    ACTION_TESTING,
    ACTION_GET_ORDER_SUMMARY_MERCHANT,

    ACTION_ADD_PLAN,
    ACTION_REMOVE_PLAN,
    DEFAULT_CURRENCY_CAD,

    METADATA_FIELD_LINK_WEBSITE,
    METADATA_FIELD_LINK_FACEBOOK,
    METADATA_FIELD_LINK_TWITTER,
    METADATA_FIELD_LINK_INSTAGRAM,
    METADATA_FIELD_LINK_LINKEDIN,
    METADATA_FIELD_LINK_YOUTUBE,
    METADATA_FIELD_MERCHANT_ID,
    METADATA_FIELD_THEME_COLOR,
    METADATA_FIELD_PRODUCT_STATUS,
    PRICE_RECURRING,
    PRICE_ONE_TIME,
    DEFAULT_COUNTRY,
    STRIPE_ACCOUNT,
    STRIPE_ACCOUNT_BUSINESS_TYPE,
    STRIPE_CHECKOUT_PAYMENT_MODE,
    STRIPE_CHECKOUT_PAYMENT_TYPE,
    EXTERNAL_BANK_ACCOUNT,
    PLATFORM_DOMAIN,
    PAYOUTS_COMMISSION_ONE_TIME,
    PAYOUTS_COMMISSION_SUBSCRIPTION_PERCENT,
    PRICES_RETRIEVAL_LIMIT_STRIPE,
    STRIPE_RETRIEVAL_LIMIT
}
