export const FETCH_SKUS_DATA = 'FETCH_SKUS_DATA';
export const FETCH_PRODUCT_DATA = 'FETCH_PRODUCT_DATA';
export const FETCH_MERCHANT_DATA = 'FETCH_MERCHANT_DATA';
export const FETCH_PRODUCT_PENDING = 'FETCH_PRODUCT_PENDING';
export const FETCH_PRODUCTS_ALL_PENDING = 'FETCH_PRODUCTS_ALL_PENDING';
export const FETCH_ERR = 'FETCH_ERR';
export const RESET_PRODUCT = 'RESET_PRODUCT';

export const ACTION_GET_MERCHANT = 'ACTION_GET_MERCHANT';
export const ACTION_CREATE_PRODUCT = 'ACTION_CREATE_PRODUCT';
export const ACTION_CREATE_MERCHANT = 'ACTION_CREATE_MERCHANT';
export const FETCH_MERCHANT_PENDING = 'FETCH_MERCHANT_PENDING';
export const FETCH_MERCHANT_ID = 'FETCH_MERCHANT_ID';
export const RESET_MERCHANT = 'RESET_MERCHANT';
export const ACTION_GET_ORDER_SUMMARY_MERCHANT = 'ACTION_GET_ORDER_SUMMARY_MERCHANT';
export const FETCH_ORDER_SUMMARY_MERCHANT = 'FETCH_ORDER_SUMMARY_MERCHANT';
